### ISSUE TITLE
headless-chromium ENOENT

### ISSUE THREAD

**Issue by JefersonS** [Tchangang/puppeteer-lambda-launcher#1]
Any reason to why I am getting this error: 

Error: Failed to launch chrome! spawn C:\Users\jefer\AppData\Local\Temp\headless-chromium ENOENT

I'm just running the Readme code, everything is set and I can even find the file when I access the said folder.
When a run it after the download I even get the message "Chrome already downloaded", but then I fall to the same error.

Am I missing something here?

**Comment by Tchangang** [comment]
Hello Jeferson, it looks like you are not running the code in AWS Lambda. If you are on Windows, you can just download Chrome canary and use it with puppeteer or just use puppeteer (they have all binaries for you). 
I wrote this lib for people who want to launch chrome headless on AWS lambda.

**Comment by JefersonS** [comment]
Yes, I forgot to come back here and remove the issue, I thought it could be ran from windows and lambda, my bad there! I'm using it in lambda now and working with no problems! Except that sometimes Lambda breaks stating that /tmp is full, but that's another problem.
